### ISSUE TITLE
Revue du 09/06/2021

### ISSUE THREAD

**Issue by princecorg** [nadaissa/IssaNada_3_03042021#1]
Bonjour Nada,

j'ai fait une inspection du rendu de ton dernier dépôt sur github-pages et tout me semble conforme aux attentes.
En mode mobile, l'animation du cœur nécessite de maintenir le clic pour être déclenchée car sinon la redirection vers le menu correspondant est effectuée.
Le cœur (mise en favori) n'est pas animé sur les pages de menu (vues desktop et mobile), est-ce volontaire ?

**Comment by nadaissa** [comment]
Bonjour Christophe,
Merci pour cette inspection.
Pour l'animation du cœur en mode mobile c'est bien le cas, étant donné qu'on nous demande de rendre toute la carte cliquable il n'était pas possible de faire autrement sans javascript ou en rendant les éléments textuels non cliquables.
Pour le cœur sur les pages de menu, logiquement une fois le site est conçu avec sa base de donnée, les cœurs de la page principale fonctionneront comme boutons de sélection (mise en favori) et le cœur sur les pages menu sélectionnées sera par défaut rempli comme indication de ce choix.  D'ailleurs sur la maquette le cœur rempli (à remplir) n'est pas celui des page de menus mais celui de la page principale.

**Comment by princecorg** [comment]
Bien argumenté 😊
Tout est donc opérationnel. Il ne te reste donc plus qu'à présenter et
valider le projet en soutenance.
Je ne doute pas de ta réussite.

**Comment by nadaissa** [comment]
Merci!
